//
//  SearchModels.swift
//  MusicApp
//
//  Created by Vadim  Gorbachev on 18.11.2019.
//  Copyright (c) 2019 Vadim  Gorbachev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum Model {
    struct Request {
        enum RequestType {
            case some
            case getTracks
        }
    }
    struct Response {
        enum ResponseType {
            case some
            case presentTracks
        }
    }
    struct ViewModel {
        enum ViewModelData {
            case some
            case displayTracks
        }
    }
  }
}
