//
//  SearchPresenter.swift
//  MusicApp
//
//  Created by Vadim  Gorbachev on 18.11.2019.
//  Copyright (c) 2019 Vadim  Gorbachev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentData(response: Search.Model.Response.ResponseType)
}

class SearchPresenter: SearchPresentationLogic {
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
  func presentData(response: Search.Model.Response.ResponseType) {
    switch response {
       case .some:
           print("presenter .some")
       case .presentTracks:
           print("presenter .presentTracks")
           viewController?.displayData(viewModel: Search.Model.ViewModel.ViewModelData.displayTracks)
    }
  }
}
