//
//  SearchModels.swift
//  MusicApp
//
//  Created by Vadim  Gorbachev on 18.11.2019.
//  Copyright (c) 2019 Vadim  Gorbachev. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum Model {
    struct Request {
        enum RequestType {
            case getTracks(searchTerm: String)
        }
    }
    struct Response {
        enum ResponseType {
            case presentTracks(searchResponse: SearchResponse?)
            case presentFooterView
        }
    }
    struct ViewModel {
        enum ViewModelData {
            case displayTracks(searchViewModel: SearchViewModel)
            case displayFooterView
        }
    }
  }
}

// MARK: SearchViewModel ( задаем имена json параметров для переименовывывания )

struct SearchViewModel {
    struct Cell: TrackCellViewModel {
        var iconUrlString: String?
        var trackName: String
        var collectionName: String
        var artistName: String
        var previewUrl: String?
    }
    let cells: [Cell]
}
